package com.wordnik.client.model

import java.math.BigDecimal
import java.util.Date


case class Execution (
  execID: String,
  orderID: String,
  clOrdID: String,
  clOrdLinkID: String,
  account: BigDecimal,
  symbol: String,
  side: String,
  lastQty: BigDecimal,
  lastPx: Double,
  underlyingLastPx: Double,
  lastMkt: String,
  lastLiquidityInd: String,
  simpleOrderQty: Double,
  orderQty: BigDecimal,
  price: Double,
  displayQty: BigDecimal,
  stopPx: Double,
  pegOffsetValue: Double,
  pegPriceType: String,
  currency: String,
  settlCurrency: String,
  execType: String,
  ordType: String,
  timeInForce: String,
  execInst: String,
  contingencyType: String,
  exDestination: String,
  ordStatus: String,
  triggered: String,
  workingIndicator: Boolean,
  ordRejReason: String,
  simpleLeavesQty: Double,
  leavesQty: BigDecimal,
  simpleCumQty: Double,
  cumQty: BigDecimal,
  avgPx: Double,
  commission: Double,
  tradePublishIndicator: String,
  multiLegReportingType: String,
  text: String,
  trdMatchID: String,
  execCost: BigDecimal,
  execComm: BigDecimal,
  homeNotional: Double,
  foreignNotional: Double,
  transactTime: Date,
  timestamp: Date
)
