package com.wordnik.client.model

import java.util.Date
case class Margin (
  account: Double,
  currency: String,
  commission: Double,
  riskLimit: Double,
  state: String,
  action: String,
  amount: Double,
  pendingCredit: Double,
  pendingDebit: Double,
  prevRealisedPnl: Double,
  prevUnrealisedPnl: Double,
  grossComm: Double,
  grossOpenCost: Double,
  grossExecCost: Double,
  grossLastValue: Double,
  riskValue: Double,
  initMargin: Double,
  maintMargin: Double,
  sessionMargin: Double,
  targetExcessMargin: Double,
  varMargin: Double,
  realisedPnl: Double,
  unrealisedPnl: Double,
  walletBalance: Double,
  marginBalance: Double,
  marginBalancePcnt: Double,
  marginLeverage: Double,
  marginUsedPcnt: Double,
  excessMargin: Double,
  excessMarginPcnt: Double,
  availableMargin: Double,
  withdrawableMargin: Double,
  timestamp: Date)

