#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGLiquidation
@end

@interface SWGLiquidation : SWGObject


@property(nonatomic) NSString* orderID;

@property(nonatomic) NSString* symbol;

@property(nonatomic) NSString* side;

@property(nonatomic) NSNumber* price;

@property(nonatomic) NSNumber* leavesQty;

@end
