package io.swagger.client.model

import org.joda.time.DateTime


case class Execution (
  execID: String,
  orderID: String,
  clOrdID: String,
  clOrdLinkID: String,
  account: Number,
  symbol: String,
  side: String,
  lastQty: Number,
  lastPx: Double,
  underlyingLastPx: Double,
  lastMkt: String,
  lastLiquidityInd: String,
  simpleOrderQty: Double,
  orderQty: Number,
  price: Double,
  displayQty: Number,
  stopPx: Double,
  pegOffsetValue: Double,
  pegPriceType: String,
  currency: String,
  settlCurrency: String,
  execType: String,
  ordType: String,
  timeInForce: String,
  execInst: String,
  contingencyType: String,
  exDestination: String,
  ordStatus: String,
  triggered: String,
  workingIndicator: Boolean,
  ordRejReason: String,
  simpleLeavesQty: Double,
  leavesQty: Number,
  simpleCumQty: Double,
  cumQty: Number,
  avgPx: Double,
  commission: Double,
  tradePublishIndicator: String,
  multiLegReportingType: String,
  text: String,
  trdMatchID: String,
  execCost: Number,
  execComm: Number,
  homeNotional: Double,
  foreignNotional: Double,
  transactTime: Date,
  timestamp: Date
  
)
